import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              <li><Link href="/">Home</Link></li>
              <li><Link href="/tab">tab</Link></li>
              <li><Link href="/topic">topic</Link></li>
              <li><Link href="/about">about</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
